sdk_path: "C:\\android-sdk"

apksigner: "C:\\android-sdk\\build-tools\\33.0.2\\apksigner.bat"

repo_url: https://antonio99021.github.io/storecentra/pruebas/repo

repo_name: REPO PRUEBAS

repo_description: Repositorio de test para soporte técnico.

repo_dir: pruebas/repo

make_v1_website: true

java_path: "C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.18.8-hotspot"
keytool: "C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.18.8-hotspot\\bin\\keytool.exe"
jarsigner: "C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.18.8-hotspot\\bin\\jarsigner.exe"

keystore: "keystore.jks"
repo_keyalias: "storecentrakey"
keystorepass: "123456"
keypass: "123456"
keydname: CN=storecentrakey, OU=F-Droid

