sdk_path: "C:\\android-sdk"

apksigner: "C:\\android-sdk\\build-tools\\33.0.2\\apksigner.bat"

repo_url: https://antonio99021.github.io/storecentra/repo

repo_name: Soporte Centra

repo_description: Repositorio oficial de aplicaciones.

make_v1_website: true

keystore: "keystore.jks"
repo_keyalias: "storecentrakey"
keystorepass: "123456"
keypass: "123456"
keydname: CN=storecentrakey, OU=F-Droid

